{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meriknow.fullname" . }}-api
  labels:
    {{- include "meriknow.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "meriknow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "meriknow.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "meriknow.fullname" . }}-config
            - secretRef:
                name: {{ include "meriknow.secretName" . }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: documents
              mountPath: {{ .Values.documentStorageRoot }}
            {{- end }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: documents
          persistentVolumeClaim:
            claimName: {{ include "meriknow.documentsPvcName" . }}
        {{- end }}
{{- end }}
