{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meriknow.secretName" . }}
  labels:
    {{- include "meriknow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
