{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meriknow.fullname" . }}-web
  labels:
    {{- include "meriknow.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "meriknow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "meriknow.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.images.web.repository }}:{{ .Values.images.web.tag }}"
          imagePullPolicy: {{ .Values.images.web.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
          envFrom:
            - configMapRef:
                name: {{ include "meriknow.fullname" . }}-config
            - secretRef:
                name: {{ include "meriknow.secretName" . }}
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: {{ .Values.web.port | quote }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: documents
              mountPath: {{ .Values.documentStorageRoot }}
            {{- end }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: documents
          persistentVolumeClaim:
            claimName: {{ include "meriknow.documentsPvcName" . }}
        {{- end }}
{{- end }}
