export {
	buildChunkingProfile,
	buildPreamble,
	CHUNK_POLICY_VERSION,
	type ChunkingOptions,
	type ChunkingProfile,
	type ChunkProfileName,
	chunkDocument,
	formatPageLabel,
} from "./chunking";
export {
	type BuildIndexPayloadOptions,
	buildIndexPayloads,
	buildSectionRecords,
	buildTableRecords,
	buildTableSummaryRecords,
	chunkRecordId,
	generationPointId,
	type IndexRecord,
	type IndexRecordType,
	type IndexWritePayload,
	IndexWritePayloadSchema,
	recordPointId,
	sectionRecordId,
	tableRecordId,
	tableSummaryRecordId,
} from "./index-records";
